"""
Nifty 500 Backtesting Framework
================================
Downloads 10 years of daily OHLCV data for selected Nifty 500 stocks
and runs a configurable strategy. All results are saved to CSV + PNG charts.

Strategies available:
  1. SMA Crossover  – Buy when 50-day SMA crosses above 200-day SMA; sell on cross below.
  2. RSI Mean-Revert – Buy when RSI(14) < 30; sell when RSI > 70.
  3. Momentum        – Buy top-N% by 12-month return each month; rebalance monthly.

Usage:
    python backtest.py                         # uses default settings
    python backtest.py --strategy sma          # SMA Crossover
    python backtest.py --strategy rsi          # RSI Mean Reversion
    python backtest.py --strategy momentum     # Momentum
    python backtest.py --tickers TCS INFY HDFCBANK --strategy sma
"""

import argparse
import os
import urllib.request
import logging
from typing import List, Dict, Optional
import warnings
warnings.filterwarnings("ignore")

import pandas as pd
import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
from datetime import datetime, timedelta

# ─────────────────────────────────────────────
#  LOGGING CONFIGURATION
# ─────────────────────────────────────────────
logging.basicConfig(level=logging.INFO, format='%(levelname)s: %(message)s')

# ─────────────────────────────────────────────
#  DEFAULT UNIVERSE  (representative Nifty 500)
# ─────────────────────────────────────────────
DEFAULT_TICKERS_NSE = [
    # IT
    "TCS", "INFY", "WIPRO", "TECHM", "HCLTECH", "MPHASIS",
    # Banking
    "HDFCBANK", "ICICIBANK", "KOTAKBANK", "AXISBANK", "SBIN", "INDUSINDBK", "BANDHANBNK",
    # NBFC / Insurance
    "BAJFINANCE", "BAJAJFINSV", "HDFCAMC", "SBILIFE", "ICICIPRU",
    # Energy
    "RELIANCE", "ONGC", "BPCL", "POWERGRID", "NTPC",
    # FMCG
    "HINDUNILVR", "ITC", "NESTLEIND", "BRITANNIA", "DABUR",
    # Auto
    "MARUTI", "TATAMOTORS", "BAJAJ-AUTO", "HEROMOTOCO", "EICHERMOT",
    # Pharma
    "SUNPHARMA", "DRREDDY", "CIPLA", "DIVISLAB",
    # Consumer
    "TITAN", "ASIANPAINT", "PIDILITIND", "HAVELLS",
    # Telecom
    "BHARTIARTL",
    # Infra
    "LT", "ADANIPORTS", "SIEMENS", "ABB",
    # Cement / Metals
    "ULTRACEMCO", "AMBUJACEM", "JSWSTEEL", "TATASTEEL",
]

START_DATE = (datetime.today() - timedelta(days=365 * 10)).strftime("%Y-%m-%d")
END_DATE   = datetime.today().strftime("%Y-%m-%d")
OUTPUT_DIR = "backtest_results"


# ═══════════════════════════════════════════════════════
#  DATA LAYER
# ═══════════════════════════════════════════════════════

def download_data(tickers: List[str], start: str, end: str,
                  data_dir: str = "data") -> Dict[str, pd.DataFrame]:
    """
    Load OHLCV data from local CSV files (generated by generate_data.py).
    Falls back to yfinance if a CSV is missing and yfinance is available.
    """
    data   = {}
    failed = []
    to_download = []
    logging.info(f"Checking local files and preparing download for {len(tickers)} tickers...")

    for tkr in tickers:
        csv_path = os.path.join(data_dir, f"{tkr}.csv")
        if os.path.exists(csv_path):
            try:
                df = pd.read_csv(csv_path, index_col="Date", parse_dates=True)
                df = df.loc[start:end]
                if len(df) >= 200:
                    data[tkr] = df[["Open", "High", "Low", "Close", "Volume"]].copy()
                    continue
            except Exception:
                pass
        to_download.append(tkr)

    if to_download:
        print(f"  [yfinance] Downloading {len(to_download)} missing tickers...")
        try:
            import yfinance as yf
            yf_symbols = [t if t.endswith(".NS") else f"{t}.NS" for t in to_download]
            # Grouping by ticker makes extraction more reliable for large sets
            bulk_df = yf.download(yf_symbols, start=start, end=end, 
                                 auto_adjust=True, progress=True, group_by='ticker')
            
            for tkr in to_download:
                yf_sym = tkr if tkr.endswith(".NS") else f"{tkr}.NS"
                try:
                    # Extract individual ticker data from bulk result
                    if len(yf_symbols) > 1:
                        ticker_df = bulk_df[yf_sym]
                    else:
                        ticker_df = bulk_df
                    
                    ticker_df = ticker_df.dropna(subset=["Close"])
                    if not ticker_df.empty:
                        data[tkr] = ticker_df[["Open", "High", "Low", "Close", "Volume"]].copy()
                        # Save to CSV for future local access
                        os.makedirs(data_dir, exist_ok=True)
                        data[tkr].to_csv(os.path.join(data_dir, f"{tkr}.csv"))
                    else:
                        failed.append(tkr)
                except Exception:
                    failed.append(tkr)
        except Exception as e:
            print(f"  X Bulk download failed: {e}")
            failed.extend(to_download)

    if failed:
        print(f"\n[Warning] Could not load: {failed}")
    print(f"[Data] Loaded {len(data)} tickers.\n")
    return data


def get_nifty_500_tickers() -> list[str]:
    """Fetch the latest Nifty 500 constituent list from NSE."""
    url = "https://archives.nseindia.com/content/indices/ind_nifty500list.csv"
    print(f"\n[Data] Fetching latest Nifty 500 list from NSE...")
    try:
        req = urllib.request.Request(url, headers={'User-Agent': 'Mozilla/5.0'})
        with urllib.request.urlopen(req) as response:
            df = pd.read_csv(response)
            tickers = df['Symbol'].tolist()
            print(f"  OK  Fetched {len(tickers)} tickers.")
            return tickers
    except Exception as e:
        print(f"  X  Failed to fetch Nifty 500 list: {e}. Falling back to default list.")
        return DEFAULT_TICKERS_NSE


# ═══════════════════════════════════════════════════════
#  INDICATORS
# ═══════════════════════════════════════════════════════

def sma(series: pd.Series, window: int) -> pd.Series:
    return series.rolling(window).mean()

def rsi(series: pd.Series, period: int = 14) -> pd.Series:
    delta = series.diff()
    gain  = delta.clip(lower=0).rolling(period).mean()
    loss  = (-delta.clip(upper=0)).rolling(period).mean()
    rs    = gain / loss.replace(0, np.nan)
    return 100 - (100 / (1 + rs))


# ═══════════════════════════════════════════════════════
#  STRATEGIES
# ═══════════════════════════════════════════════════════

def strategy_sma_crossover(df: pd.DataFrame,
                            fast: int = 50,
                            slow: int = 200) -> pd.Series:
    """
    Signal = +1 when 50-SMA > 200-SMA, 0 otherwise (long-only).
    Entry/exit on next day's open after signal fires.
    """
    price  = df["Close"]
    fast_s = sma(price, fast)
    slow_s = sma(price, slow)
    signal = (fast_s > slow_s).astype(int)
    return signal.shift(1).fillna(0)          # execute next day


def strategy_rsi_mean_revert(df: pd.DataFrame,
                              period: int = 14,
                              oversold: float = 30,
                              overbought: float = 70) -> pd.Series:
    """
    Buy when RSI drops below `oversold`; sell when RSI rises above `overbought`.
    """
    r      = rsi(df["Close"], period)
    pos    = pd.Series(0, index=df.index)
    in_pos = False
    for i in range(len(r)):
        if pd.isna(r.iloc[i]):
            pos.iloc[i] = 0
            continue
        if not in_pos and r.iloc[i] < oversold:
            in_pos = True
        elif in_pos and r.iloc[i] > overbought:
            in_pos = False
        pos.iloc[i] = 1 if in_pos else 0
    return pos.shift(1).fillna(0)


def strategy_momentum(data: dict[str, pd.DataFrame],
                       lookback: int = 252,
                       top_pct: float = 0.25) -> dict[str, pd.Series]:
    """
    Monthly rebalance: hold the top `top_pct` of stocks by trailing `lookback`-day return.
    Returns a dict of {ticker: signal_series}.
    """
    closes = pd.DataFrame({t: d["Close"] for t, d in data.items()}).dropna(how="all")
    monthly_dates = closes.resample("ME").last().index

    signals = {t: pd.Series(0.0, index=closes.index) for t in closes.columns}

    for i in range(1, len(monthly_dates)):
        rebal_date = monthly_dates[i]
        # Use index position for safe slicing
        rebal_pos  = closes.index.get_indexer([rebal_date], method="ffill")[0]
        look_pos   = max(0, rebal_pos - lookback)

        window = closes.iloc[look_pos : rebal_pos + 1]
        if len(window) < 20:
            continue
        ret  = window.iloc[-1] / window.iloc[0] - 1
        ret  = ret.dropna()
        n    = max(1, int(len(ret) * top_pct))
        top  = ret.nlargest(n).index.tolist()

        # Hold from this rebalance to next
        next_pos = (closes.index.get_indexer([monthly_dates[i + 1]], method="ffill")[0]
                    if i + 1 < len(monthly_dates) else len(closes))

        for t in top:
            if t in signals:
                signals[t].iloc[rebal_pos : next_pos] = 1.0

    return {t: s.shift(1).fillna(0) for t, s in signals.items()}


# ═══════════════════════════════════════════════════════
#  PERFORMANCE ENGINE
# ═══════════════════════════════════════════════════════

def compute_returns(df: pd.DataFrame, signal: pd.Series) -> pd.DataFrame:
    """Daily strategy returns vs buy-and-hold."""
    close = df["Close"]
    daily_ret   = close.pct_change().fillna(0)
    strat_ret   = daily_ret * signal
    bah_ret     = daily_ret

    equity_strat = (1 + strat_ret).cumprod()
    equity_bah   = (1 + bah_ret).cumprod()

    return pd.DataFrame({
        "daily_strat":  strat_ret,
        "daily_bah":    bah_ret,
        "equity_strat": equity_strat,
        "equity_bah":   equity_bah,
        "signal":       signal,
    })


def max_drawdown(equity: pd.Series) -> float:
    roll_max = equity.cummax()
    dd = (equity - roll_max) / roll_max
    return dd.min()


def cagr(equity: pd.Series) -> float:
    years = (equity.index[-1] - equity.index[0]).days / 365.25
    if years <= 0:
        return 0.0
    return (equity.iloc[-1] / equity.iloc[0]) ** (1 / years) - 1


def sharpe(returns: pd.Series, rf: float = 0.06) -> float:
    """Annualised Sharpe (risk-free = 6% p.a. as proxy for India)."""
    excess = returns - rf / 252
    if excess.std() == 0:
        return 0.0
    return np.sqrt(252) * excess.mean() / excess.std()


def summarise(res: pd.DataFrame, ticker: str) -> dict:
    strat = res["equity_strat"]
    bah   = res["equity_bah"]
    exposure = res["signal"].mean()
    trades   = int(res["signal"].diff().abs().sum() / 2)
    return {
        "Ticker":              ticker,
        "Strategy CAGR (%)":   round(cagr(strat)      * 100, 2),
        "B&H CAGR (%)":        round(cagr(bah)         * 100, 2),
        "Strategy Sharpe":     round(sharpe(res["daily_strat"]), 2),
        "B&H Sharpe":          round(sharpe(res["daily_bah"]),   2),
        "Strategy MaxDD (%)":  round(max_drawdown(strat) * 100, 2),
        "B&H MaxDD (%)":       round(max_drawdown(bah)    * 100, 2),
        "Strategy Final (Rs)":  round(strat.iloc[-1], 4),
        "B&H Final (Rs)":       round(bah.iloc[-1],   4),
        "Market Exposure (%)": round(exposure * 100, 1),
        "Trades":              trades,
    }


# ═══════════════════════════════════════════════════════
#  CHARTS
# ═══════════════════════════════════════════════════════

def plot_equity(results: dict[str, pd.DataFrame], strategy_name: str, out_dir: str):
    """Plot equity curves for all tickers."""
    n   = len(results)
    cols = min(3, n)
    rows = (n + cols - 1) // cols
    fig, axes = plt.subplots(rows, cols, figsize=(6 * cols, 4 * rows))
    axes = np.array(axes).flatten() if n > 1 else [axes]

    fig.suptitle(f"Equity Curves - {strategy_name}\n(Rs1 invested at start)",
                 fontsize=14, fontweight="bold", y=1.01)

    for idx, (tkr, res) in enumerate(results.items()):
        ax = axes[idx]
        ax.plot(res.index, res["equity_strat"], color="#1f77b4", lw=1.5, label="Strategy")
        ax.plot(res.index, res["equity_bah"],   color="#ff7f0e", lw=1.2, ls="--", label="Buy & Hold")
        ax.set_title(tkr, fontsize=10, fontweight="bold")
        ax.set_ylabel("Equity (Rs)")
        ax.legend(fontsize=7)
        ax.grid(True, alpha=0.3)
        # shade in-market periods
        sig = res["signal"].reindex(res.index).fillna(0)
        ax.fill_between(res.index, 0, res["equity_strat"].max() * 1.05,
                        where=sig > 0, alpha=0.07, color="green", label="_nolegend_")

    # Hide unused subplots
    for j in range(idx + 1, len(axes)):
        axes[j].set_visible(False)

    plt.tight_layout()
    path = os.path.join(out_dir, "equity_curves.png")
    plt.savefig(path, dpi=120, bbox_inches="tight")
    plt.close()
    print(f"[Chart] Saved: {path}")


def plot_summary_bar(summary_df: pd.DataFrame, strategy_name: str, out_dir: str):
    """Bar chart comparing Strategy vs B&H CAGR."""
    fig, axes = plt.subplots(1, 2, figsize=(14, 5))
    fig.suptitle(f"Strategy Summary - {strategy_name}", fontsize=13, fontweight="bold")

    x  = np.arange(len(summary_df))
    w  = 0.35
    tk = summary_df["Ticker"].tolist()

    # CAGR
    ax = axes[0]
    ax.bar(x - w/2, summary_df["Strategy CAGR (%)"], w, label="Strategy", color="#1f77b4")
    ax.bar(x + w/2, summary_df["B&H CAGR (%)"],      w, label="Buy & Hold", color="#ff7f0e")
    ax.set_title("CAGR (%)")
    ax.set_xticks(x); ax.set_xticklabels(tk, rotation=45, ha="right", fontsize=8)
    ax.axhline(0, color="black", lw=0.5)
    ax.legend(); ax.grid(axis="y", alpha=0.3)

    # Max Drawdown
    ax = axes[1]
    ax.bar(x - w/2, summary_df["Strategy MaxDD (%)"], w, label="Strategy", color="#1f77b4")
    ax.bar(x + w/2, summary_df["B&H MaxDD (%)"],      w, label="Buy & Hold", color="#ff7f0e")
    ax.set_title("Max Drawdown (%) - lower is better")
    ax.set_xticks(x); ax.set_xticklabels(tk, rotation=45, ha="right", fontsize=8)
    ax.legend(); ax.grid(axis="y", alpha=0.3)

    plt.tight_layout()
    path = os.path.join(out_dir, "summary_bars.png")
    plt.savefig(path, dpi=120, bbox_inches="tight")
    plt.close()
    print(f"[Chart] Saved: {path}")


def plot_aggregate_equity(results: dict[str, pd.DataFrame], strategy_name: str, out_dir: str):
    """Equal-weight portfolio equity curve."""
    equities_strat = pd.DataFrame({t: r["equity_strat"] for t, r in results.items()})
    equities_bah   = pd.DataFrame({t: r["equity_bah"]   for t, r in results.items()})

    port_strat = equities_strat.mean(axis=1)
    port_bah   = equities_bah.mean(axis=1)

    fig, ax = plt.subplots(figsize=(12, 5))
    ax.plot(port_strat.index, port_strat, color="#1f77b4", lw=2, label="Equal-Weight Portfolio - Strategy")
    ax.plot(port_bah.index,   port_bah,   color="#ff7f0e", lw=1.5, ls="--", label="Equal-Weight Portfolio - Buy & Hold")
    ax.set_title(f"Equal-Weight Portfolio Equity - {strategy_name}", fontsize=13, fontweight="bold")
    ax.set_ylabel("Portfolio Value (Rs1 = base)")
    ax.legend(); ax.grid(True, alpha=0.3)
    plt.tight_layout()
    path = os.path.join(out_dir, "portfolio_equity.png")
    plt.savefig(path, dpi=120, bbox_inches="tight")
    plt.close()
    print(f"[Chart] Saved: {path}")


# ═══════════════════════════════════════════════════════
#  MAIN ORCHESTRATOR
# ═══════════════════════════════════════════════════════

def run_backtest(tickers: list[str], strategy: str, out_dir: str, data_dir: str = "data"):
    os.makedirs(out_dir, exist_ok=True)

    # 1. Download data
    data = download_data(tickers, START_DATE, END_DATE, data_dir=data_dir)
    if not data:
        print("[Error] No data downloaded. Exiting.")
        return

    # 1b. Consolidate closing prices (Requirement: 500 companies at once)
    closes_df = pd.DataFrame({tkr: df["Close"] for tkr, df in data.items()})
    consolidated_path = os.path.join(out_dir, "nifty500_all_closes.csv")
    closes_df.to_csv(consolidated_path)
    print(f"[Data] Consolidated daily closing prices (10 yrs) saved to: {consolidated_path}")

    # 2. Pre-compute momentum signals (needs all tickers)
    momentum_signals = {}
    if strategy == "momentum":
        print("[Strategy] Computing momentum signals (this may take a moment) ...")
        momentum_signals = strategy_momentum(data)

    # 3. Run strategy per ticker
    results  = {}
    summaries = []
    STRATEGY_LABEL = {
        "sma":      "SMA Crossover (50/200)",
        "rsi":      "RSI Mean Reversion (14, 30/70)",
        "momentum": "12-Month Momentum (Top 25%)",
    }
    label = STRATEGY_LABEL.get(strategy, strategy)

    print(f"[Backtest] Running '{label}' on {len(data)} stocks ...\n")

    for ticker, df in data.items():
        if strategy == "sma":
            signal = strategy_sma_crossover(df)
        elif strategy == "rsi":
            signal = strategy_rsi_mean_revert(df)
        elif strategy == "momentum":
            signal = momentum_signals.get(ticker, pd.Series(0, index=df.index))
        else:
            raise ValueError(f"Unknown strategy: {strategy}")

        res = compute_returns(df, signal)
        results[ticker]  = res
        summaries.append(summarise(res, ticker))

    # 4. Save summary CSV
    summary_df = pd.DataFrame(summaries).sort_values("Strategy CAGR (%)", ascending=False)
    csv_path   = os.path.join(out_dir, "backtest_summary.csv")
    summary_df.to_csv(csv_path, index=False)
    print(f"\n[Results] Summary saved to: {csv_path}")

    # 5. Print table
    print("\n" + "=" * 90)
    print(f"  BACKTEST RESULTS - {label}")
    print("=" * 90)
    print(summary_df.to_string(index=False))
    print("=" * 90)

    # Portfolio aggregate
    port_strat = pd.DataFrame({t: r["equity_strat"] for t, r in results.items()}).mean(axis=1)
    port_bah   = pd.DataFrame({t: r["equity_bah"]   for t, r in results.items()}).mean(axis=1)
    print(f"\n  EQUAL-WEIGHT PORTFOLIO")
    print(f"  Strategy CAGR : {cagr(port_strat)*100:.2f}%   |   "
          f"B&H CAGR : {cagr(port_bah)*100:.2f}%")
    print(f"  Strategy MaxDD: {max_drawdown(port_strat)*100:.2f}%   |   "
          f"B&H MaxDD: {max_drawdown(port_bah)*100:.2f}%")
    print(f"  Strategy Sharpe: {sharpe(port_strat.pct_change().dropna()):.2f}   |   "
          f"B&H Sharpe: {sharpe(port_bah.pct_change().dropna()):.2f}")
    print("=" * 90 + "\n")

    # 6. Charts
    plot_equity(results, label, out_dir)
    plot_summary_bar(summary_df, label, out_dir)
    plot_aggregate_equity(results, label, out_dir)

    # 7. Save individual equity CSVs
    for ticker, res in results.items():
        res.to_csv(os.path.join(out_dir, f"{ticker}_equity.csv"))

    print(f"\n[Done] All outputs in: ./{out_dir}/")


# ═══════════════════════════════════════════════════════
#  CLI
# ═══════════════════════════════════════════════════════

if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Nifty 500 Backtesting Framework",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__
    )
    parser.add_argument(
        "--tickers", nargs="+", default=DEFAULT_TICKERS_NSE,
        help="NSE ticker symbols (without .NS suffix)"
    )
    parser.add_argument(
        "--strategy", choices=["sma", "rsi", "momentum"], default="sma",
        help="Strategy to backtest (default: sma)"
    )
    parser.add_argument(
        "--out", default=OUTPUT_DIR,
        help="Output directory for results (default: backtest_results)"
    )
    parser.add_argument(
        "--data-dir", default="data",
        help="Directory with per-ticker CSV files (default: data)"
    )
    parser.add_argument(
        "--nifty500", action="store_true",
        help="Fetch and use all 500 Nifty 500 tickers"
    )
    args = parser.parse_args()

    ticker_list = get_nifty_500_tickers() if args.nifty500 else args.tickers

    run_backtest(
        tickers  = ticker_list,
        strategy = args.strategy,
        out_dir  = args.out,
        data_dir = args.data_dir,
    )
